on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium-chrome:
        image: selenium/standalone-chrome:latest # 3.141.59
        ports:
          - 4444:4444
        options: --shm-size="2g"
      selenium-firefox:
        image: selenium/standalone-firefox:latest # 3.141.59
        ports:
          - 4445:4444
        options: --shm-size="2g"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.5.5'
        bundler-cache: true
    - name: Selenium Run
      run: |
        ls -al
        echo
        curl -I localhost:4444 || exit 0
        curl -I localhost:4445 || exit 0
        echo
        bundle install
        ruby selenium.rb
        ls -al
